2024-08-01 20:58:46,004 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Владислав\Desktop\Программирование\UrbanUniversity\Модуль 12\module_12_4\tests_12_4.py", line 27, in test_run
    runner = Runner(1)
             ^^^^^^^^^
  File "C:\Users\Владислав\Desktop\Программирование\UrbanUniversity\Модуль 12\module_12_4\module_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
2024-08-01 20:58:46,005 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Владислав\Desktop\Программирование\UrbanUniversity\Модуль 12\module_12_4\tests_12_4.py", line 15, in test_walk
    runner = Runner(-1)
             ^^^^^^^^^^
  File "C:\Users\Владислав\Desktop\Программирование\UrbanUniversity\Модуль 12\module_12_4\module_12_4.py", line 6, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
